# Generated by Django 4.2.11 on 2024-12-19 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizhistory_completed_date_quizhistory_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
