# Generated by Django 4.2.5 on 2024-11-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_remove_question_type_delete_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
