# Generated by Django 4.2.5 on 2024-11-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
    ]
