# Generated by Django 4.2.5 on 2024-12-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='correct_option',
            field=models.CharField(default='', max_length=255),
        ),
    ]
