# Generated by Django 4.2.5 on 2024-12-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quiz_correct_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_option',
        ),
    ]
