# Generated by Django 4.2.5 on 2024-12-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_quiz_correct_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizhistory',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='quizhistory',
            name='is_correct',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
