# Generated by Django 4.2.5 on 2024-12-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_quizhistory_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='options',
            field=models.TextField(),
        ),
    ]
